# Generated by Django 5.0.2 on 2024-03-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_symptom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
