# Generated by Django 5.0.2 on 2024-03-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_patient_symptoms_delete_symptom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='symptom',
            field=models.ManyToManyField(to='website.symptom'),
        ),
    ]
