# Generated by Django 5.0.2 on 2024-03-03 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_symptom_name_symptom_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='symptom',
            new_name='symptoms',
        ),
    ]
